// This file is generated by scripts/generate-data-files.mjs.
// Do not edit it by hand; update data/*.json and run npm run generate:data-manifest.

import catalogManifest from "../../data/catalog.json"
import documentsData from "../../data/documents/index.json"
import requirementsData from "../../data/requirements/index.json"
import countryGE from "../../data/countries/GE.json"
import countryRS from "../../data/countries/RS.json"
import countryAM from "../../data/countries/AM.json"
import countryTR from "../../data/countries/TR.json"
import countryKZ from "../../data/countries/KZ.json"
import countryKG from "../../data/countries/KG.json"
import countryUZ from "../../data/countries/UZ.json"
import countryME from "../../data/countries/ME.json"
import countryVN from "../../data/countries/VN.json"
import countryTH from "../../data/countries/TH.json"
import countryAE from "../../data/countries/AE.json"
import countryCY from "../../data/countries/CY.json"
import countryES from "../../data/countries/ES.json"
import countryPT from "../../data/countries/PT.json"
import countryDE from "../../data/countries/DE.json"
import countryFR from "../../data/countries/FR.json"
import countryPL from "../../data/countries/PL.json"
import countryBG from "../../data/countries/BG.json"
import countryHU from "../../data/countries/HU.json"
import countryIT from "../../data/countries/IT.json"
import sourcesGE from "../../data/sources/GE.json"
import sourcesRS from "../../data/sources/RS.json"
import sourcesAM from "../../data/sources/AM.json"
import sourcesTR from "../../data/sources/TR.json"
import sourcesKZ from "../../data/sources/KZ.json"
import sourcesKG from "../../data/sources/KG.json"
import sourcesUZ from "../../data/sources/UZ.json"
import sourcesME from "../../data/sources/ME.json"
import sourcesVN from "../../data/sources/VN.json"
import sourcesTH from "../../data/sources/TH.json"
import sourcesAE from "../../data/sources/AE.json"
import sourcesCY from "../../data/sources/CY.json"
import sourcesES from "../../data/sources/ES.json"
import sourcesPT from "../../data/sources/PT.json"
import sourcesDE from "../../data/sources/DE.json"
import sourcesFR from "../../data/sources/FR.json"
import sourcesPL from "../../data/sources/PL.json"
import sourcesBG from "../../data/sources/BG.json"
import sourcesHU from "../../data/sources/HU.json"
import sourcesIT from "../../data/sources/IT.json"
import routesGE from "../../data/routes/GE.json"
import routesRS from "../../data/routes/RS.json"
import routesAM from "../../data/routes/AM.json"
import routesTR from "../../data/routes/TR.json"
import routesKZ from "../../data/routes/KZ.json"
import routesKG from "../../data/routes/KG.json"
import routesUZ from "../../data/routes/UZ.json"
import routesME from "../../data/routes/ME.json"
import routesVN from "../../data/routes/VN.json"
import routesTH from "../../data/routes/TH.json"
import routesAE from "../../data/routes/AE.json"
import routesCY from "../../data/routes/CY.json"
import routesES from "../../data/routes/ES.json"
import routesPT from "../../data/routes/PT.json"
import routesDE from "../../data/routes/DE.json"
import routesFR from "../../data/routes/FR.json"
import routesPL from "../../data/routes/PL.json"
import routesBG from "../../data/routes/BG.json"
import routesHU from "../../data/routes/HU.json"
import routesIT from "../../data/routes/IT.json"

export const rawDataCatalog = {
  manifest: catalogManifest,
  countries: [
    countryGE,
    countryRS,
    countryAM,
    countryTR,
    countryKZ,
    countryKG,
    countryUZ,
    countryME,
    countryVN,
    countryTH,
    countryAE,
    countryCY,
    countryES,
    countryPT,
    countryDE,
    countryFR,
    countryPL,
    countryBG,
    countryHU,
    countryIT,
  ],
  sources: [
    ...sourcesGE,
    ...sourcesRS,
    ...sourcesAM,
    ...sourcesTR,
    ...sourcesKZ,
    ...sourcesKG,
    ...sourcesUZ,
    ...sourcesME,
    ...sourcesVN,
    ...sourcesTH,
    ...sourcesAE,
    ...sourcesCY,
    ...sourcesES,
    ...sourcesPT,
    ...sourcesDE,
    ...sourcesFR,
    ...sourcesPL,
    ...sourcesBG,
    ...sourcesHU,
    ...sourcesIT,
  ],
  requirements: requirementsData,
  documents: documentsData,
  routes: [
    ...routesGE,
    ...routesRS,
    ...routesAM,
    ...routesTR,
    ...routesKZ,
    ...routesKG,
    ...routesUZ,
    ...routesME,
    ...routesVN,
    ...routesTH,
    ...routesAE,
    ...routesCY,
    ...routesES,
    ...routesPT,
    ...routesDE,
    ...routesFR,
    ...routesPL,
    ...routesBG,
    ...routesHU,
    ...routesIT,
  ],
}
